version: '3'
services:  
  node-exporter:
    container_name: monitor-node-exporter
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - node-exporter-net

networks:
  node-exporter-net:
    driver: bridge